language: android
jdk:
  - oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - tools
  - extra-android-m2repository
  - build-tools-25.0.2
  - build-tools-26.0.0
  - android-25
  - android-26
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
before_script:
  - yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses
script:
  - ./gradlew dtglib:build dtgqueue:build
after_success:
  - ./travis-push-to-bintray.sh
notifications:
  email:
    recipients:
      - noam.tamim@kaltura.com
      - gilad.nadav@kaltura.com
      - Anton.Afanasiev@kaltura.com
    on_success: change
    on_failure: always
